version: "3.9"
services:
    web:
        build: .
        ports:
            - "5001:5001"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            MSSQL_SA_PASSWORD: "@lerDev.sql"
            ACCEPT_EULA: "Y"