CREATE TABLE users
(
    idUser INT IDENTITY(1,1) NOT NULL,
    firstName VARCHAR(155) NOT NULL  ,
    lastName VARCHAR(155) NOT NULL  ,
    email VARCHAR(155) NOT NULL UNIQUE ,
    password TEXT NOT NULL  ,
    systemDate DATETIME NOT NULL DEFAULT (GETDATE()),
	status BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_users PRIMARY KEY CLUSTERED (idUser ASC) ON [PRIMARY]
)

CREATE TABLE roles
(
    idRol INT IDENTITY(1,1) NOT NULL,
    code VARCHAR(255) NOT NULL UNIQUE,
	description VARCHAR(255) NOT NULL,
    systemDate DATETIME NOT NULL DEFAULT (GETDATE()),
	status BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_roles PRIMARY KEY CLUSTERED (idRol ASC) ON [PRIMARY]
)

CREATE TABLE policy
(
    idPolicy INT IDENTITY(1,1) NOT NULL,
    code VARCHAR(255) NOT NULL UNIQUE,
	description VARCHAR(255) NOT NULL,
    route VARCHAR(155) NOT NULL,
    systemDate DATETIME NOT NULL DEFAULT (GETDATE()),
	status BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_policy PRIMARY KEY CLUSTERED (idPolicy ASC) ON [PRIMARY]
)

CREATE TABLE rolPolicy
(
    idRolPolicy INT IDENTITY(1,1) NOT NULL,
    idRol INT NOT NULL,
    idPolicy INT NOT NULL,
	status BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_rolPolicy PRIMARY KEY CLUSTERED (idRolPolicy ASC) ON [PRIMARY],
    FOREIGN KEY (idRol) REFERENCES roles(idRol),
    FOREIGN KEY (idPolicy) REFERENCES policy(idPolicy)
)

CREATE TABLE userRol
(
    idUserRol INT IDENTITY(1,1) NOT NULL,
    idUser INT NOT NULL,
    idRol INT NOT NULL,
	status BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_userRol PRIMARY KEY CLUSTERED (idUserRol ASC) ON [PRIMARY],
    FOREIGN KEY (idUser) REFERENCES users(idUser),
    FOREIGN KEY (idRol) REFERENCES roles(idRol)
)
